/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface XCkeditor {
    'config': string;
    'content': string;
    'editor': string;
    'targetId': string;
  }
  interface XCkeditorAttributes extends StencilHTMLAttributes {
    'config'?: string;
    'content'?: string;
    'editor'?: string;
    'onCkeditorchange'?: (event: CustomEvent) => void;
    'targetId'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'XCkeditor': Components.XCkeditor;
  }

  interface StencilIntrinsicElements {
    'x-ckeditor': Components.XCkeditorAttributes;
  }


  interface HTMLXCkeditorElement extends Components.XCkeditor, HTMLStencilElement {}
  var HTMLXCkeditorElement: {
    prototype: HTMLXCkeditorElement;
    new (): HTMLXCkeditorElement;
  };

  interface HTMLElementTagNameMap {
    'x-ckeditor': HTMLXCkeditorElement
  }

  interface ElementTagNameMap {
    'x-ckeditor': HTMLXCkeditorElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
